services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/mini_artemis
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery:
    build: .
    command: celery -A app.celery_worker.celery worker --loglevel=info
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/mini_artemis
      - CELERY_BROKER_URL=redis://redis:6379/0

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_artemis
    ports:
      - "5432:5432"

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
